#include-once

#Region Inventory
; Inventory Array
Global Enum _
    $GC_I_INVENTORY_PTR = 0, _
    $GC_I_INVENTORY_ITEMID, _
    $GC_I_INVENTORY_BAG, _
    $GC_I_INVENTORY_ITEMTYPE, _
    $GC_I_INVENTORY_EXTRAID, _
    $GC_I_INVENTORY_VALUE, _
    $GC_I_INVENTORY_ISIDENTIFIED, _
    $GC_I_INVENTORY_ISINSCRIBABLE, _
    $GC_I_INVENTORY_MODELID, _
    $GC_I_INVENTORY_RARITY, _
    $GC_I_INVENTORY_ISMATERIALSALVAGEABLE, _
    $GC_I_INVENTORY_QUANTITY, _
    $GC_I_INVENTORY_SLOT

; Storage
Global Enum _
	$GC_I_INVENTORY_UNUSED_BAG, $GC_I_INVENTORY_BACKPACK, _
	$GC_I_INVENTORY_BELT_POUCH, $GC_I_INVENTORY_BAG1, _
	$GC_I_INVENTORY_BAG2, $GC_I_INVENTORY_EQUIPMENT_PACK, _
	$GC_I_INVENTORY_MATERIAL_STORAGE, $GC_I_INVENTORY_UNCLAIMED_ITEMS, _
    $GC_I_INVENTORY_STORAGE1, $GC_I_INVENTORY_STORAGE2, _
	$GC_I_INVENTORY_STORAGE3, $GC_I_INVENTORY_STORAGE4, _
	$GC_I_INVENTORY_STORAGE5, $GC_I_INVENTORY_STORAGE6, _
	$GC_I_INVENTORY_STORAGE7, $GC_I_INVENTORY_STORAGE8, _
	$GC_I_INVENTORY_STORAGE9, $GC_I_INVENTORY_STORAGE10, _
	$GC_I_INVENTORY_STORAGE11, $GC_I_INVENTORY_STORAGE12, _
	$GC_I_INVENTORY_STORAGE13, $GC_I_INVENTORY_STORAGE14, _
	$GC_I_INVENTORY_EQUIPPED_ITEMS
#EndRegion Inventory

#Region Materials
; Material
Global Const $GC_I_MODELID_BONES = 921
Global Const $GC_I_MODELID_CLOTHS = 925
Global Const $GC_I_MODELID_DUST = 929
Global Const $GC_I_MODELID_FEATHERS = 933
Global Const $GC_I_MODELID_PLANT_FIBRES = 934
Global Const $GC_I_MODELID_TANNED_HIDE = 940
Global Const $GC_I_MODELID_WOOD = 946
Global Const $GC_I_MODELID_IRON = 948
Global Const $GC_I_MODELID_SCALES = 953
Global Const $GC_I_MODELID_CHITIN = 954
Global Const $GC_I_MODELID_GRANITE = 955

; Rare Material
Global Const $GC_I_MODELID_CHARCOAL = 922
Global Const $GC_I_MODELID_MONSTROUS_CLAW = 923
Global Const $GC_I_MODELID_LINEN = 926
Global Const $GC_I_MODELID_DAMASK = 927
Global Const $GC_I_MODELID_SILK = 928
Global Const $GC_I_MODELID_GLOB_OF_ECTOPLASM = 930
Global Const $GC_I_MODELID_MONSTROUS_EYE = 931
Global Const $GC_I_MODELID_MONSTROUS_FANG = 932
Global Const $GC_I_MODELID_DIAMOND = 935
Global Const $GC_I_MODELID_ONYX = 936
Global Const $GC_I_MODELID_RUBY = 937
Global Const $GC_I_MODELID_SAPPHIRE = 938
Global Const $GC_I_MODELID_GLASS_VIAL = 939
Global Const $GC_I_MODELID_FUR_SQUARE = 941
Global Const $GC_I_MODELID_LEATHER_SQUARE = 942
Global Const $GC_I_MODELID_ELONIAN_LEATHER_SQUARE = 943
Global Const $GC_I_MODELID_VIAL_OF_INK = 944
Global Const $GC_I_MODELID_OBSIDIAN_SHARD = 945
Global Const $GC_I_MODELID_STEEL_INGOT = 949
Global Const $GC_I_MODELID_DELDRIMOR_STEEL_INGOT = 950
Global Const $GC_I_MODELID_ROLL_OF_PARCHMENT = 951
Global Const $GC_I_MODELID_ROLL_OF_VELLUM = 952
Global Const $GC_I_MODELID_SPIRITWOOD_PLANK = 956
Global Const $GC_I_MODELID_AMBER_CHUNK = 6532
Global Const $GC_I_MODELID_JADEIT_SHARD = 6533

Global Const $GC_AI_MATERIALS[11] = [ _
	$GC_I_MODELID_BONES, _
	$GC_I_MODELID_CLOTHS, _
	$GC_I_MODELID_DUST, _
	$GC_I_MODELID_FEATHERS, _
	$GC_I_MODELID_PLANT_FIBRES, _
    $GC_I_MODELID_TANNED_HIDE, _
	$GC_I_MODELID_WOOD, _
	$GC_I_MODELID_IRON, _
	$GC_I_MODELID_SCALES, _
	$GC_I_MODELID_CHITIN, _
	$GC_I_MODELID_GRANITE _
]

Global Const $GC_AI_RARE_MATERIALS[25] = [ _
	$GC_I_MODELID_CHARCOAL, _
	$GC_I_MODELID_MONSTROUS_CLAW, _
	$GC_I_MODELID_LINEN, _
	$GC_I_MODELID_DAMASK, _
	$GC_I_MODELID_SILK, _
	$GC_I_MODELID_GLOB_OF_ECTOPLASM, _
	$GC_I_MODELID_MONSTROUS_EYE, _
	$GC_I_MODELID_MONSTROUS_FANG, _
	$GC_I_MODELID_DIAMOND, _
	$GC_I_MODELID_ONYX, _
	$GC_I_MODELID_RUBY, _
	$GC_I_MODELID_SAPPHIRE, _
	$GC_I_MODELID_GLASS_VIAL, _
	$GC_I_MODELID_FUR_SQUARE, _
	$GC_I_MODELID_LEATHER_SQUARE, _
	$GC_I_MODELID_ELONIAN_LEATHER_SQUARE, _
	$GC_I_MODELID_VIAL_OF_INK, _
	$GC_I_MODELID_OBSIDIAN_SHARD, _
	$GC_I_MODELID_STEEL_INGOT, _
	$GC_I_MODELID_DELDRIMOR_STEEL_INGOT, _
	$GC_I_MODELID_ROLL_OF_PARCHMENT, _
	$GC_I_MODELID_ROLL_OF_VELLUM, _
	$GC_I_MODELID_SPIRITWOOD_PLANK, _
	$GC_I_MODELID_AMBER_CHUNK, _
	$GC_I_MODELID_JADEIT_SHARD _
]

Global Const $GC_AI_ALL_MATERIALS[36] = [ _
	$GC_I_MODELID_BONES, _
	$GC_I_MODELID_CHARCOAL, _
	$GC_I_MODELID_MONSTROUS_CLAW, _
	$GC_I_MODELID_CLOTHS, _
	$GC_I_MODELID_LINEN, _
	$GC_I_MODELID_DAMASK, _
	$GC_I_MODELID_SILK, _
	$GC_I_MODELID_DUST, _
	$GC_I_MODELID_GLOB_OF_ECTOPLASM, _
	$GC_I_MODELID_MONSTROUS_EYE, _
	$GC_I_MODELID_MONSTROUS_FANG, _
	$GC_I_MODELID_FEATHERS, _
	$GC_I_MODELID_PLANT_FIBRES, _
	$GC_I_MODELID_DIAMOND, _
	$GC_I_MODELID_ONYX, _
	$GC_I_MODELID_RUBY, _
	$GC_I_MODELID_SAPPHIRE, _
	$GC_I_MODELID_GLASS_VIAL, _
	$GC_I_MODELID_FUR_SQUARE, _
	$GC_I_MODELID_LEATHER_SQUARE, _
	$GC_I_MODELID_ELONIAN_LEATHER_SQUARE, _
	$GC_I_MODELID_VIAL_OF_INK, _
	$GC_I_MODELID_TANNED_HIDE, _
	$GC_I_MODELID_OBSIDIAN_SHARD, _
	$GC_I_MODELID_WOOD, _
	$GC_I_MODELID_IRON, _
	$GC_I_MODELID_STEEL_INGOT, _
	$GC_I_MODELID_DELDRIMOR_STEEL_INGOT, _
	$GC_I_MODELID_ROLL_OF_PARCHMENT, _
	$GC_I_MODELID_ROLL_OF_VELLUM, _
	$GC_I_MODELID_SCALES, _
	$GC_I_MODELID_CHITIN, _
	$GC_I_MODELID_GRANITE, _
	$GC_I_MODELID_SPIRITWOOD_PLANK, _
	$GC_I_MODELID_AMBER_CHUNK, _
	$GC_I_MODELID_JADEIT_SHARD _
]
#EndRegion Materials