#include-once

#Include "SmartCast_Attack.au3"
#Include "SmartCast_Chant.au3"
#Include "SmartCast_EchoRefrain.au3"
#Include "SmartCast_Enchantment.au3"
#Include "SmartCast_Form.au3"
#Include "SmartCast_Glyph.au3"
#Include "SmartCast_Hex.au3"
#Include "SmartCast_ItemSpell.au3"
#Include "SmartCast_PetAttack.au3"
#Include "SmartCast_Preparation.au3"
#Include "SmartCast_Ritual.au3"
#Include "SmartCast_Shout.au3"
#Include "SmartCast_Signet.au3"
#Include "SmartCast_Skill10.au3"
#Include "SmartCast_Skill16.au3"
#Include "SmartCast_Spell.au3"
#Include "SmartCast_Stance.au3"
#Include "SmartCast_Title.au3"
#Include "SmartCast_Trap.au3"
#Include "SmartCast_Ward.au3"
#Include "SmartCast_WeaponSpell.au3"
#Include "SmartCast_Well.au3"
